# Làm quen với Pytorch

Pytorch được cài đặt sẵn trong Google colab nên sẽ không cần phải tải lại. Tuy nhiên nếu dùng trên máy cá nhận thì người dùng cần phải tải gói về sử dụng terminal. Trong trường hợp này thì người dùng sẽ cần phải kiểm tra các gói cần thiết cũng như độ tương thích ở trang https://pytorch.org/

Đầu tiên chúng ta sẽ kiểm tra phiên bản pytorch sử dụng trên colab

In [1]:
import torch

print(torch.__version__)

2.5.1+cu124


## 1. Tensors

Một số kiểu dữ liệu mà tensor có thể lưu trữ được được liệt kê trong trang sau: https://pytorch.org/docs/stable/tensors.html

### Tạo các Tensors


In [2]:
# Scalar (0D tensor)
scalar = torch.tensor(5)
print(scalar) # Giá trị của tensor
print(type(scalar)) # Loại dữ liệu tensor
print(scalar.ndim)  # Số chiều của tensor
print(scalar.item())  # Giá trị số học mà tensor chứa

tensor(5)
<class 'torch.Tensor'>
0
5


In [3]:
# Vector
vector = torch.tensor([1, 2, 3])
print(vector)
print(type(vector))
print(vector.ndim)
print(vector.shape) # Kích cỡ mỗi chiều của tensor

tensor([1, 2, 3])
<class 'torch.Tensor'>
1
torch.Size([3])


In [4]:
# Matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(type(matrix))
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>
2
torch.Size([2, 3])


In [5]:
# Tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(tensor)
print(type(tensor))
print(tensor.ndim)
print(tensor.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
<class 'torch.Tensor'>
3
torch.Size([2, 2, 3])


### Random Tensors

Torch random numbers: https://pytorch.org/docs/main/generated/torch.rand.html

In [6]:
random_tensor = torch.rand(3, 4)

print(random_tensor)
print(type(random_tensor))
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.9039, 0.7933, 0.5006, 0.6352],
        [0.1813, 0.6373, 0.5225, 0.0741],
        [0.2597, 0.6090, 0.2809, 0.6719]])
<class 'torch.Tensor'>
2
torch.Size([3, 4])


### Zeros and Ones

In [7]:
# Tạo một tensor chỉ có giá trị 0
zeros = torch.zeros(3, 4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [8]:
# Tạo một tensor chỉ có giá trị 1
ones = torch.ones(3, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Range and tensors-like

In [9]:
range = torch.range(0, 10)
print(range.dtype)

torch.float32


<ipython-input-9-be6c1e8fcc3c>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(0, 10)


In [10]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
zeros_like_tensors = torch.zeros_like(range)
print(zeros_like_tensors)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


### Tensor datatypes

Trong pytorch, neếu không có các khai báo bổ sung thì kiểu dữ liệu mặc định sẽ là kiểu dữ liệu được nhập vào. Một số kiểu dữ liệu trong tensor: https://pytorch.org/docs/stable/tensors.html

In [12]:
# Float32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,          # Kiểu dữ liệu của tensor
                               device=None,         # Thiết bị sẽ được sử dụng để tính toán và lưu trữ dữ liệu, thường có CPU và Cuda
                               requires_grad=False) # Quyết định xem PyTorch có cần tính toán và lưu trữ gradient cho tensor đó hay không trong quá trình lan truyền ngược
print(float_32_tensor.dtype)

torch.float32


### Manipulating tensors

Có 5 phép toán cơ bản với tensor, bao gồm:
- Cộng
- Trừ
- Nhân
- Chia
- Nhân ma trận

In [13]:
tensor = torch.tensor([1, 2, 3])

# Phép cộng
print(tensor + 10) # hoặc sử dụng torch.add

# Phép trừ
print(tensor - 10)  # hoặc sử dụng torch.sub

# Phép nhân
print(tensor * 10)  # hoặc sử dụng torch.mul

# Phép chia
print(tensor / 10)  # hoặc sử dụng torch.div

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [14]:
# Nhân ma trận

new_tensor = torch.matmul(tensor, tensor)
print(new_tensor)

tensor(14)


Trong khi thực hiện phép nhân ma trận, một trong những lỗi thường gặp đó là lỗi shape của hai ma trận không thể thực hiện việc nhân ma trận. Một trong các cách khắc phục vấn đề này là sử dụng phép Transpose

In [15]:
tensorA = torch.rand(3,2)
tensorB = torch.rand(3,2)

print(tensorA)
print(tensorB)

new_tensorB = tensorB.T

print(tensorA)
print(new_tensorB)
print(torch.matmul(tensorA, new_tensorB))

tensor([[0.5789, 0.6973],
        [0.2960, 0.8517],
        [0.5268, 0.0466]])
tensor([[0.4385, 0.4646],
        [0.7796, 0.6320],
        [0.5499, 0.7837]])
tensor([[0.5789, 0.6973],
        [0.2960, 0.8517],
        [0.5268, 0.0466]])
tensor([[0.4385, 0.7796, 0.5499],
        [0.4646, 0.6320, 0.7837]])
tensor([[0.5778, 0.8919, 0.8648],
        [0.5254, 0.7690, 0.8302],
        [0.2527, 0.4402, 0.3263]])


## 2. Một số hàm hữu dụng với Tensors

### Tensor Aggregation (min, max, sum, ...)

In [16]:
x = torch.rand(3, 4)
print(x)
print(f"min của tensor là: {x.max()}")
print(f"max của tensor là: {x.min()}")
print(f"sum của tensor là: {x.sum()}")
print(f"mean của tensor là: {x.mean()}")

tensor([[0.8974, 0.6024, 0.8007, 0.2932],
        [0.6292, 0.7013, 0.8539, 0.5928],
        [0.7859, 0.0177, 0.9754, 0.0149]])
min của tensor là: 0.9753790497779846
max của tensor là: 0.01491457223892212
sum của tensor là: 7.164950370788574
mean của tensor là: 0.5970792174339294


Đôi khi giá trị cần được trả về không phải là giá trị thỏa mãn hàm mà là vị trí của trí trí của giá trị này, lúc này ta làm như sau

In [17]:
print(f"vị trí min của tensor là: {x.argmax()}")
print(f"vị trí max của tensor là: {x.argmin()}")

vị trí min của tensor là: 10
vị trí max của tensor là: 11


### Reshape, Stacking, Squeezing and Unsqeezing

1. Reshape: thay đổi kích thước (shape) của một tensor mà không làm thay đổi tổng số phần tử.

2. View:  thay đổi hình dạng (reshape) của tensor nhưng không thay đổi bộ nhớ gốc

3. Stacking: thao tác xếp chồng nhiều tensor dọc theo một chiều mới (tăng số chiều của tensor).

4. Squeezing: thao tác loại bỏ các chiều có kích thước 1 khỏi tensor.

5. Unsqueezing: thao tác thêm một chiều có kích thước 1 vào tensor.

6. Permute: hoán đổi thứ tự các chiều (axes) của tensor, nhưng không thay đổi dữ liệu trong bộ nhớ.

In [18]:
# Reshape
x = torch.arange(1., 10.)
print(x, x.shape)

x_reshaped = x.reshape(3, 3)
print(x_reshaped, x_reshaped.shape)


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) torch.Size([3, 3])


In [19]:
# View

z = x.view(3, 3)
print(z, x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [20]:
# Stack
# HStack
x_stacked = torch.stack([x, x, x, x], dim=0)
print(x_stacked)

# VStack
x_stacked = torch.vstack([x, x, x, x])
print(x_stacked)

# HStack
x_stacked = torch.hstack([x, x, x, x])
print(x_stacked)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [21]:
# Squeeze

x = torch.tensor([[1, 2, 3, 4]])

x_squeezed = x.squeeze()
print(x_squeezed, x_squeezed.shape)

tensor([1, 2, 3, 4]) torch.Size([4])


In [22]:
# Unsqueeze

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed, x_unsqueezed.shape)

tensor([[1, 2, 3, 4]]) torch.Size([1, 4])


In [23]:
# Permute

x_original = torch.rand(size=(1, 2, 3))
print(x_original, x_original.shape)

x_permuted = x_original.permute(2, 0, 1)
print(x_permuted, x_permuted.shape)

tensor([[[0.7027, 0.5327, 0.7460],
         [0.1051, 0.3283, 0.6413]]]) torch.Size([1, 2, 3])
tensor([[[0.7027, 0.1051]],

        [[0.5327, 0.3283]],

        [[0.7460, 0.6413]]]) torch.Size([3, 1, 2])


### Selecting data (Indexing)

In [24]:
x  = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [25]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
x[0, 0]

tensor([1, 2, 3])

In [27]:
x[0, 0, 0]

tensor(1)

In [28]:
x[:, :2, 1]

tensor([[2, 5]])

### Pytorch and Numpy

https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

In [29]:
import numpy as np
arr = np.array([1, 2, 3])

# Chuyển từ np sang tensor
tensor = torch.from_numpy(arr)
print(tensor)

# Chuyển ngược lại
arr = tensor.numpy()
print(arr)

tensor([1, 2, 3])
[1 2 3]


### Reproducibility

In [30]:
randomA = torch.rand(3, 4)
randomB = torch.rand(3, 4)

print(randomA)
print(randomB)
print(randomA == randomB)

tensor([[0.5431, 0.3840, 0.0243, 0.1309],
        [0.9206, 0.7459, 0.9424, 0.4150],
        [0.5875, 0.2414, 0.5052, 0.1128]])
tensor([[0.5591, 0.2744, 0.8205, 0.1730],
        [0.0274, 0.1235, 0.8480, 0.1153],
        [0.6549, 0.6731, 0.9053, 0.3644]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Quá trình tái tạo có thể được thực hiện bằng cách đặt một seed trước khi chạy hàm một hàm random

In [31]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
randomC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
randomD = torch.rand(3, 4)

print(randomC)
print(randomD)
print(randomC == randomD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## 3. Truy cập và sử dụng GPU

In [33]:
!nvidia-smi

Sat Feb  1 19:24:02 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [34]:
# Kiểm tra kết nối với Pytorch
torch.cuda.is_available()

True

In [35]:
# Sử dụng GPU để lưu trữ
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device="cuda")
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


Numpy chỉ hoạt động trên CPU nên nếu cần tính toán trên Numpy thì cần chuyển dữ liệu về CPU để lưu trữ và tính toán